### ISSUE TITLE
Input validation and ng-required

### ISSUE THREAD

**Issue by LiamK** [mareczek/international-phone-number#31]
Hi -- I am using it in a form in which the phone number is not required, it is optional.

However, the phone number apparently *is* required, regardless of the presence of "required" or ng-required="false".

I expect form.$invalid to be false (if all the other required fields are filled in), but the form is always invalid unless there is a valid phone number entered.

What should I do to make the phone number optional?

**Comment by mareczek** [comment]
I just pushed a new version, please checkout 0.0.6 and let me know if the problem persists

**Comment by mareczek** [comment]
I just confirmed, ng-required cooperates with international-phone-number

**Comment by LiamK** [comment]
I have done some more testing and now it's behaving differently, but not quite right, still.  There seems to be some kind of interaction with other input elements.  

There are 3 inputs, 1 textarea and 1 international-phone-number element.  

The elements that are required (or ng-required) no longer seem to affect the value of form.$invalid.  
form.fullname.$invalid can be true, but form.$invalid is still false.  I think if a form element is invalid the form should also be invalid itself.

For that reason, the blank form starts as valid, since the required fields are ignored.

A focus + unfocus on the international-phone-number element makes form.$invalid = true.  It shouldn't!

If required fields are filled in and I focus + backspace on the international-phone-number, then form.$invalid = false, but it should be true.

Could you please take another look at this?  Really appreciate your help.

**Comment by ravitejadeevi** [comment]
I am facing exactly the same problem. ( as mentioned by @LiamK ).
I appreciate your help.

Thanks.

**Comment by LiamK** [comment]
Ravi,

Did you check out the pull request I made?
I fixed this a little while ago.

Liam

**Comment by ravitejadeevi** [comment]
Yes @LiamK, I saw the pull request. I am gonna implement it. Thanks for ur help. I will let u know, if
any issues.

Thanks.

**Comment by ravitejadeevi** [comment]
@LiamK I pulled your code from lkfix branch and integrated into my code. But it didn't work for me.
I still have the same problem. I couldn't understand the reason. Do i need to modify something in html code or just including your changes is enough ?

Thanks.

**Comment by LiamK** [comment]
Ravi,

I wish I had more time to help!  However,  here is how I am using it.  I 
tested it with and without required.

  <input international-phone-number
                    preferred-countries="us"
                    default-country="us"
                    national-mode="true"
utils-script="/static/bower_components/intl-tel-input/lib/libphonenumber/build/utils.js"
                    responsive-dropdown="true"
                    class="form-control"
                    type="phone"
                    id="phone"
                    name="phone"
                    type="tel"
                    ng-model-options="{'debounce':1500}"
                    ng-model="main.contactFormParams.contact_phone"
                     />

Liam
