### ISSUE TITLE
form.$invalid = true after loading correct data without focusing international-phone-number element

### ISSUE THREAD

**Issue by sergeymurashko** [mareczek/international-phone-number#58]
Hi Mareczek,

I have a form where I'm trying to edit phone number with international-phone-number element. After loading form I'm able to see data in input element (it contains valid phone number), but form has form.$invalid = true.
Focus this element makes form.$invalid = false. 

Could you please look at this case? Thanks in advance.

**Comment by mareczek** [comment]
Hi, I have the same problem. Will be fixing this really soon :-)

**Comment by 7867praveen** [comment]
@sergeymurashko I have the same problem but I used a temporary solution. Use $pristine with $invalid so on load only validate if filed is edited.

**Comment by mareczek** [comment]
Should be fixed in 0.0.11

**Comment by antoinepairet** [comment]
@mareczek I just updated to 0.0.11. The issue is still present.
regards

**Comment by antoinepairet** [comment]
@mareczek I can confirm the issue is fixed. Thanks!
